### PR TITLE
Fixing barlinechart component

### PR DESCRIPTION
**Pull request by Agroang**
# Description

# Type of change

Please mark 'X' as appropriate:

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix/feature update (non-breaking change which fixes an issue/changes functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Manual testing with current master. Working as expected.

### CODE REVIEW

**Comment by VivianBao** [comment]
Thanks @Agroang! I tested on local and it looks good to me! @khatakslied when you have the time please give it a look and feel free to merge : )

**Comment by VivianBao** [comment]
Thanks @Agroang! I tested on local and it looks good to me! @khatakslied when you have the time please give it a look and feel free to merge : ) 

[Posted again to test if it appears on Slack channel, bear with me!]

**Review by VivianBao — APPROVED** [review]

**Comment by Agroang** [comment]
@VivianBao Wonder if we can just merge it 😆, might take a while to get the second review depending on how busy Ryan is.

**Comment by VivianBao** [comment]
@Agroang Indeed. Since this is part of the tickets we discussed together I think it is safe to merge! Once merged I will pull from master to my branches to resolve conflicts if there are any. I will let you know again once all conflicts are cleared!

@khatakslied I will be merging this PR! We can discuss further changes if you have some new ideas!

**Pull request merged**
